2019-02-28 18:16:59,286 - public_methods.py[line:66] - INFO: 获取ID时报错，错误为:<urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>,url为:http://10.82.2.29:7010/api/v1.0/one/dsl/query?dsl={"Salesman":{"fields":["id","PersonnelNumber"],"cond":{"in":{"PersonnelNumber":["0041","0118","02824","05160","06040","123456","123457","22370"]}},"limit":500}}
2019-02-28 18:16:59,286 - public_methods.py[line:66] - INFO: 获取ID时报错，错误为:<urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>,url为:http://10.82.2.29:7010/api/v1.0/one/dsl/query?dsl={"Salesman":{"fields":["id","PersonnelNumber"],"cond":{"in":{"PersonnelNumber":["0041","0118","02824","05160","06040","123456","123457","22370"]}},"limit":500}}
